作業目標<br>
讀取存取陣列資料<br>
作業重點<br>
多陣列存一起需要存成npz，讀取須注意npz中有多個陣列

題目:<br>
1. 將下兩列array存成npz檔<br>
array1 = np.array(range(30))<br>
array2 = np.array([2,3,5])<br>
2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔


In [3]:
import numpy as np

In [4]:
#. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])

In [5]:
#方法一
with open('D06-homework.npz', 'wb') as f:
    np.savez(f, array1=array1, array2=array2)

In [7]:
#方法二
np.savez('array.npz',array1,array2)

In [8]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔
aa=np.load('D06-homework.npz')
print(aa['array1'])
print(aa['array2'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [10]:
#方法一
with open('D06-homework2.npz', 'wb') as f2:
    np.savez(f2, array1=aa['array1'], array2=aa['array2'],array3=np.array([1,2,4,6,7]))

In [11]:
bb=np.load('D06-homework2.npz')
print(bb['array1'])
print(bb['array2'])
print(bb['array3'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[1 2 4 6 7]


In [17]:
#方法二
np.savez('ttl.npz',array1=aa['array1'],array2=aa['array2'],array3=np.array([1,2,4,6,7]))

In [19]:
bb=np.load('ttl.npz')
print(bb['array1'])
print(bb['array2'])
print(bb['array3'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[1 2 4 6 7]
